#pragma once

namespace tur
{
	enum class PrimitiveTopology
	{
		POINTS,
		LINES,
		LINE_STRIPS,
		TRIANGLES,
		TRAIANGLE_STRIPS,
		TRIANGLE_FANS,
		LINES_WITH_ADJACENCY,
		LINE_STRIPS_WITH_ADJACENCY,
		TRIANGLES_WITH_ADJACENCY,
		TRIANGLE_STRIPS_WITH_ADJACENCY,
		PATCHES,
	};
}